### ISSUE TITLE
Causal Estimators

### ISSUE THREAD

**Issue by AndrewC19** [CITCOM-project/CausalTestingFramework#14]
## Overview
Given a Causal DAG and a dataframe containing data for each variable in the DAG, we need to be able to estimate the effect of a treatment (X) on an outcome (Y). This corresponds to an edge (X --> Y) in the causal DAG.

Using our Causal DAG class, we can now identify a minimal adjustment set relative to the effect of X on Y i.e. a set of variables that, once adjusted for, isolates the **causal effect** of X on Y (according to the assumptions encoded in the DAG).

Next, we need statistical estimators which are capable of estimating the effect of X on Y in the data while adjusting for the minimal adjustment set. This should yield the average treatment effect (causal effect) of X on Y and, optionally, 95% (Wald) confidence intervals for this estimate.

We do not want to implement estimators from scratch as plenty exist in libraries such as ![EconML](https://github.com/microsoft/EconML). However, we want to provide a "contract" which states the assumptions that must be hold if the causal estimate it to be considered truly causal. Therefore, for each estimator, we need to store a list of assumptions that can be reported with the causal estimate e.g. linear mean model of the form `Y ~ V0 + V1*X1` is only valid if the X/Y relationship can be captured by a straight line, whereas the linear mean model `Y ~ V0 + V1*X1 + V2*X1^2` is valid if the X/Y relationship can be captured by a parabola (or a straight line in which cae `V2=0`). I will add a follow-up issue which sets out the structure for these "contracts" at a later date.

While there isn't a method to check whether a causal estimate is correct, we can make our assumptions clear so that any other tester/modeller has the opportunity to dispute our claims. To make the tester/modeller's life as easy as possible, we should collect the assumptions automatically.

## Background on estimators
In general, we have two forms of estimator: parameteric and non-parametric. A parametric estimator places some restriction on the shape of data (e.g. must be a straight line) and uses this constraint to borrow data from neighbours. A non-parametric estimator places no (or very little) constraints on the shape of the data and thus borrows no (or very little) information from neighbours. As a consequence, non-parametric estimators are not suitable for estimating the outcome for a treatment value that has no been observed (doesn't appear in the data). 

For example, suppose we want to estimate the effect of a vaccine on cumulative infections in an epidemiological model. We identify age as a confounder (it affects both the likelihood someone recevies a vaccine and the likelihood they become infected). We have data for age groups 0-20, 20-40, 60-80, and 80+ but we are missing data for  40-60. Stratification is a non-parametric estimator where we average the causal effect in each of the age groups. Clearly, we cannot use stratification because we are missing data for 40-60. On the other hand, linear regression is a parametric estimator. If we are willing to accept the assumption that the relationship between vaccine, cumulative infections, and age is some linear combination of variables (e.g. `infections ~ V0 + V1*vaccine + V2*age` meaning the relationship forms a flat plane), we can extraploate to borrow information from the neighbouring age groups 20-40 and 60-80. Note that this is only valid if the modelling assumption holds. If the relationships between vaccine and infections forms a straight line but the form of this straightline changes with age, for example, then we would need an equation of the form `infections ~ V0 + V1*vaccine + V2*age + V3*age^2` (a curved plane) otherwise our extrapolated values would be invalid and we would yield a biased estimate.

## Tasks
- [x] Implement an abstract base class for an estimator. This should contain the necessary information to run the estimator (treatment variables, treatment value, control  value, confounders, effect modifiers etc.) as well as a method for collecting/forming the assumptions.
- [x] Implement a LinearEstimator class.
- [x] Implement a CausalRandomForestEstimator class.
- [x] Add tests for estimators which compare achieved estimates to those in the code examples of Chapter 2 in [Hernans and Robins book, _What if?_](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/)

**Comment by AndrewC19** [comment]
Currently have a LinearEstimator class which is capable of estimating the ATE of a treatment on an outcome. Still need to work out how to compute conditional average treatment effect for a list of effect modifiers.

**Comment by AndrewC19** [comment]
We now have a linear estimator and causal random forest estimator class. 

I don't think it is necessary to add any more estimators at this stage. For the purpose of the paper, I think it is enough to have one parametric estimator and one non-parametric estimator. What are your thoughts @jmafoster1 and @neilwalkinshaw?

In addition, the class is set up in a way that allows users to implement their own estimator fairly easily, requiring two methods to be implemented: `estimate_ate` and `add_modelling_assumptions`. The former would be the method that handles estimation and the latter requires users to record any modelling assumptions.

Whilst the modelling assumptions implementation is overly simplistic at the moment (the estimator object stores a list of strings corresponding to modelling assumptions given by the user), it serves an important purpose: to communicate the conditions under which the results of causal inference (and therefore the causal test results) are valid. Ultimately, we want to produce a report or contract which enumerates these assumptions (along with identifiability assumptions). This report would be attached to the results of a causal test case along with the causal DAG, since this information determines the validity of the test outcome.

**Comment by jmafoster1** [comment]
I agree. I don't think there's much point in implementing loads of estimators just for the sake of it. If it's easy, we can do them as and when we need to, especially if we can plug in existing stuff from scikit learn or EconML or whatever.

I think it'd be good, at some point, to have it so the modelling assumptions are presented as a list of conditions (probably functions which take in data and return a bool) which can be automatically checked against the data to see if it's valid.

**Comment by neilwalkinshaw** [comment]
Hi Andy - excellent work. I completely agree - leave it as it is for now, great that it's extensible.

**Comment by AndrewC19** [comment]
Great, thanks both. 

I'll close this issue for now and re-open in the future if and when we need to add/refine the estimators.

**Comment by AndrewC19** [comment]
Also, regarding your suggestion @jmafoster1, I really like the idea of implementing modelling assumptions which can be automatically checked. This would require some further reading and implementation changes, but definitely worth including in a future iteration.
